# MODE
MODE=paper  # Change to "live" after testing!

# EXCHANGE & SYMBOLS
SYMBOLS=BTC/USDT:USDT,ETH/USDT:USDT,LINK/USDT:USDT,LTC/USDT:USDT
# ✅ REMOVED SOL - It has terrible win rate

# TIMEFRAMES
ENTRY_TF="1h"
HTF="4h"
LOOKBACK_DAYS=180

# CAPITAL
TOTAL_PORTFOLIO_CAPITAL=10000
PER_COIN_ALLOCATION=0.25
# With 4 coins: $2,500 per coin

# RISK MANAGEMENT
RISK_PERCENT=0.02
RR_FIXED=5.0
DYNAMIC_RR=true
MIN_RR=4.0
MAX_RR=6.0

# STOPS & INDICATORS
USE_ATR_STOPS=true
ATR_PERIOD=14
ATR_MULT_SL=1.5
USE_H1_FILTER=true

# FILTERS
USE_VOLUME_FILTER=false
RSI_PERIOD=14
RSI_OVERSOLD=25
BIAS_CONFIRM_BEAR=8
# ✅ CHANGED FROM 2 TO 8 - Less aggressive exits
COOLDOWN_HOURS=0.0

# POSITION LIMITS
MAX_DRAWDOWN=0.20
MAX_TRADE_SIZE=100000
MAX_POSITION_PCT=0.5
# ✅ NEW: Max 50% of capital per position

# FEES
SLIPPAGE_RATE=0.0005
FEE_RATE=0.0006
INCLUDE_FUNDING=true

# TELEGRAM (futures bot)
TELEGRAM_TOKEN_FUT=your_telegram_bot_token_here
TELEGRAM_CHAT_ID_FUT=your_telegram_chat_id_here

# KUCOIN API (for live mode)
KUCOIN_API_KEY=your_api_key_here
KUCOIN_SECRET=your_secret_here
KUCOIN_PASSPHRASE=your_passphrase_here

# SCHEDULING
SEND_DAILY_SUMMARY=true
SUMMARY_HOUR=20
SLEEP_CAP=60

